pipeline {
    agent any

    tools {
        nodejs 'node18'
    }

    environment {
        SERVICE_NAME = "taskManager-frontend"
        IMAGE_NAME = "manasacloud001/taskmanager-frontend:latest"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('frontend') {
                    sh 'docker build --build-arg VITE_API_URL=http://backend:4000 -t  ${IMAGE_NAME} .'
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-hub-creds',
                    usernameVariable: 'DOCKER_USERNAME',
                    passwordVariable: 'DOCKER_PASSWORD'
                )]) {
                    sh """
                        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                        docker push ${IMAGE_NAME}
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Frontend pipeline completed successfully"
        }
        failure {
            echo "Frontend pipeline failed"
        }
    }
}
