pipeline {
  agent any

  tools {
    nodejs 'node-18'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('backend') {
          sh 'npm install'
        }
      }
    }

    stage('Run Tests') {
      steps {
        dir('backend') {
          sh 'npm test'
        }
      }
    }

    stage('Build') {
      steps {
        dir('backend') {
          sh 'npm run build'
        }
      }
    }
  }
}
